name: 'Google Drive tools Action - send'
description: 'This action sends a file to Google Drive'
inputs:
  file_id:
    description: 'The ID of the file or shared drive.'
    required: false
    default: ''
  parent_id:
    description: 'The ID of the parent folders in remote'
    required: false
    default: ''
  dest_file_name:
    description: 'The name of the file in remote'
    required: false
    default: ''
  src_file_name:
    description: 'The name(path) of the file in local filesystem'
    required: true
    default: ''
  dest_mime_type:
    description: 'The MIME type of the file.'
    required: false
    default: ''
  src_mime_type:
    description: 'Media mime-type'
    required: false
    default: ''
outputs:
  file_id:
    description: 'The ID of the file that is sended into Google Drive'
runs:
  using: 'node16'
  main: 'dist/index.js'
