name: 'Google Drive tools Action - send'
description: 'This action sends a file to Google Drive'
inputs:
  file_id:
    description: 'The ID of the file or shared drive.'
    required: false
    default: ''
  parent_id:
    description: 'The ID of the parent folders in remote'
    required: false
    default: ''
  dest_file_name:
    description: 'The name of the file in remote'
    required: false
    default: ''
  src_file_name:
    description: 'The name(path) of the file in local filesystem'
    required: true
    default: ''
  dest_mime_type:
    description: 'The MIME type of the file.'
    required: false
    default: ''
  src_mime_type:
    description: 'Media mime-type'
    required: false
    default: ''
  supports_all_drives:
    description: 'Supports both My Drives and shared drives(`includeItemsFromAllDrives` is also enabled)'
    required: false
    default: ''
outputs:
  file_id:
    description: 'The ID of the file that is sended into Google Drive. Be careful, the ID of the file can also be sensitive data.'
runs:
  using: 'node20'
  main: 'dist/index.mjs'
branding:
  icon: 'upload-cloud'
  color: 'blue'
